# <font color='blue'><b> <center> NUMPY </center></b></font>

In [30]:
import numpy as np

## Indexado

In [26]:
# A 3-Dimensional array
a = np.array([[0, 1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10, 11],
              [12, 13, 14, 15, 16, 17],
              [18, 19, 20, 21, 22, 23],
              [24, 25, 26, 27, 28, 29],
              [30, 31, 32, 33, 34, 35]])
print("\n Array is:\n ",a)
 
print("\n")
print("shape",a.shape)
    
# slicing and indexing
print("\n a[0, 3:5]  = ",a[0, 3:5]) 
 
print("\n a[4:, 4:]  = ",a[4:, 4:]) 
 
print("\n a[:, 2]  = ",a[:, 2]) 
 
print("\n a[2::2, ::2]  = ",a[2::2, ::2]) 


 Array is:
  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


shape (6, 6)

 a[0, 3:5]  =  [3 4]

 a[4:, 4:]  =  [[28 29]
 [34 35]]

 a[:, 2]  =  [ 2  8 14 20 26 32]

 a[2::2, ::2]  =  [[12 14 16]
 [24 26 28]]


<img src="images/slicing.png">

In [6]:
x[-2]

8

In [11]:
# veamos un arreglo bidimensional

x.shape = (2,5)

print(x)

print(x.shape)


[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


In [13]:
x[1,3] # fila 1, columna 3; recuerdo que las filas arrancan en 0!

8

In [14]:
x[0,2]

2

In [16]:
x[1,-1] # último elemento de la fila 1

9

In [17]:
#Note that if one indexes a multidimensional array with fewer indices than dimensions, 
#one gets a subdimensional array. For example:

x[0]

array([0, 1, 2, 3, 4])

Lo que se retorna es una vista, no es una copia del arreglo original, sino que apunta a los mismos valores que el original.



### Slicing and striding

Basic slicing extends Python’s basic concept of slicing to N dimensions. Basic slicing occurs when obj is a slice object (constructed by start:stop:step notation inside of brackets), an integer, or a tuple of slice objects and integers. Ellipsis and newaxis objects can be interspersed with these as well.

The simplest case of indexing with N integers returns an array scalar representing the corresponding item. As in Python, all indices are zero-based: for the i-th index
, the valid range is where is the i-th element of the shape of the array. Negative indices are interpreted as counting from the end of the array (i.e., if , it means

).

All arrays generated by basic slicing are always views of the original array.

The standard rules of sequence slicing apply to basic slicing on a per-dimension basis (including using a step index). Some useful concepts to remember include:


- The basic slice syntax is i:j:k where i is the starting index, j is the stopping index, and k is the step (). This selects the m elements (in the corresponding dimension) with index values i, i + k, …, i + (m - 1) k where and q and r are the quotient and remainder obtained by dividing j - i by k: j - i = q k + r, so that i + (m - 1) k < j. For example:

In [31]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(x)

print(x.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [32]:
x[1:7:2] # del 1 al 7 con un paso de 2

array([1, 3, 5])

Negative i and j are interpreted as n + i and n + j where n is the number of elements in the corresponding dimension. Negative k makes stepping go towards smaller indices. From the above example:

In [29]:
x[-2:10] # últimos 2


array([8, 9])

In [30]:
x[-4:10] # últimos 4

array([6, 7, 8, 9])

In [35]:
x[-3:3:-1] # desde el tercer elemento desde atrás, al tercer elemento, con un paso de -1

array([7, 6, 5, 4])

In [36]:
x[-3:3:-2]

array([7, 5])

In [37]:
x[-2:3:-1]

array([8, 7, 6, 5, 4])

Assume n is the number of elements in the dimension being sliced. Then, if i is not given it defaults to 0 for k > 0 and n - 1 for k < 0 . If j is not given it defaults to n for k > 0 and -n-1 for k < 0 . If k is not given it defaults to 1. Note that :: is the same as : and means select all indices along this axis. From the above example:

In [38]:
x[5:] # elementos desde el 5 en adelante

array([5, 6, 7, 8, 9])

If the number of objects in the selection tuple is less than N, then : is assumed for any subsequent dimensions. For example:

In [40]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])


print(x)
print()
print(x.shape)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]

(2, 3, 1)


In [79]:

#  1 2 3
#  4 5 6
# + prof.


x[1:2] # filas de la 1 a la 2; todo lo que venga en la columna ;todo lo que venga en prfundidad
# idem que x[1:2,:,:]

array([[[4],
        [5],
        [6]]])

In [48]:
x[0:2] 

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [53]:
primera_columna = x[:, 0, :]
primera_columna

array([[1],
       [4]])

In [52]:
primera_fila = x[0, :, :]
primera_fila

array([[1],
       [2],
       [3]])

In [54]:
x[:, :,0]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
x[1] # segunda fila + prof.

array([[4],
       [5],
       [6]])

In [57]:
x[0] # primer fila + prof.

array([[1],
       [2],
       [3]])

In [60]:
x[0:2]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

### Dimensional indexing tools

There are some tools to facilitate the easy matching of array shapes with expressions and in assignments.

Ellipsis expands to the number of : objects needed for the selection tuple to index all dimensions. In most cases, this means that the length of the expanded selection tuple is x.ndim. There may only be a single ellipsis present. From the above example:

In [80]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])

x, x.shape

(array([[[1],
         [2],
         [3]],
 
        [[4],
         [5],
         [6]]]),
 (2, 3, 1))

In [83]:

x[..., 0] # idem que x[:, :, 0]


array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
x[0,...] # mismo que x[0,:,:]

array([[1],
       [2],
       [3]])

Each newaxis object in the selection tuple serves to expand the dimensions of the resulting selection by one unit-length dimension. The added dimension is the position of the newaxis object in the selection tuple. newaxis is an alias for None, and None can be used in place of this with the same result. From the above example:

In [87]:
print(x.shape)

x[:, np.newaxis, :, :].shape

(2, 3, 1)


(2, 1, 3, 1)

In [88]:
#https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/

In [106]:
a3 = np.array([
                [
                    [10, 11, 12], [13, 14, 15], [16, 17, 18]
                ],
                [
                    [20, 21, 22], [23, 24, 25], [26, 27, 28]
                ],
                [
                    [30, 31, 32], [33, 34, 35], [36, 37, 38]
                ]
            ])

a3.shape

(3, 3, 3)

<img src="images/tridimensional.png">

In [90]:
a3

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38]]])

In [99]:
a3[:,0,:] # fila 0 de cada uno; 

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [101]:
a3[:,:,0] # columna 0; valor de k?

array([[10, 13, 16],
       [20, 23, 26],
       [30, 33, 36]])

In [100]:
a3[0,:,:] # profundidad 0

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [102]:
a3[0,0,:]

array([10, 11, 12])

In [104]:
a3[:,0,0]

array([10, 20, 30])

In [105]:
a3[0,:,0]

array([10, 13, 16])

A 3D array is like a stack of matrices:

    The first index, i, selects the matrix
    The second index, j, selects the row
    The third index, k, selects the column


En un arreglo tridimensional (3D) en NumPy, cada dimensión representa una "dimensión" diferente en el conjunto de datos. Vamos a describir qué representa cada cosa en un arreglo 3D:

    Primera Dimensión (Eje 0):
        Esta dimensión se refiere a las "capas" o "slices" del arreglo.
        Cada elemento a lo largo de esta dimensión es una matriz bidimensional, que se puede pensar como una "hoja" del arreglo tridimensional.
        Por ejemplo, si tienes un arreglo tridimensional de forma (3, 2, 2), significa que hay 3 capas, cada una de las cuales es una matriz de 2x2.

    Segunda Dimensión (Eje 1):
        Esta dimensión representa las filas dentro de cada "capa" o "slice".
        Cada elemento a lo largo de esta dimensión es una fila en la matriz bidimensional de cada capa.
        Siguiendo el ejemplo, en un arreglo tridimensional de forma (3, 2, 2), hay 2 filas en cada capa.

    Tercera Dimensión (Eje 2):
        Esta dimensión representa las columnas dentro de cada "capa" o "slice".
        Cada elemento a lo largo de esta dimensión es una columna en la matriz bidimensional de cada capa.
        En el ejemplo (3, 2, 2), hay 2 columnas en cada capa.

En resumen, en un arreglo tridimensional, la primera dimensión representa diferentes "niveles" o "capas", la segunda dimensión representa las filas dentro de cada capa, y la tercera dimensión representa las columnas dentro de cada capa. Puedes acceder a elementos individuales utilizando la notación de indexación, especificando el índice a lo largo de cada dimensión.

<img src="images/axis_new.png">

In [4]:


# arreglo de (2,3,4)

import numpy as np


aux = np.arange(24).reshape(2,3,4)

aux

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [10]:
print(aux[0,:,:]) # primera profundidad
print()
print(aux[0,:,:].shape) # 3 filas, 4 columnas


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

(3, 4)


In [12]:
print(aux[:,0,:]) # primera fila de cada capa de profundidad
print()
print(aux[:,0,:].shape) # 2,4 (2 de prof, 4 cols)

[[ 0  1  2  3]
 [12 13 14 15]]

(2, 4)


In [13]:
print(aux[:,:,0]) # primera columna de cada capa
print()
print(aux[:,:,0].shape) # 2, 3

[[ 0  4  8]
 [12 16 20]]

(2, 3)


In [15]:
aux[...,0] # ídem que aux[:,:,0]

array([[ 0,  4,  8],
       [12, 16, 20]])

In [16]:
aux[0,...] # ídem que aux[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
aux[0,...,0] # agarra estas posiciones (0, 0, 0), (0, 1, 0) y (0, 2, 0) 

array([0, 4, 8])

In [21]:


aux[:,:,-2] # anteúltima columna de cada capa de profundidad


array([[ 2,  6, 10],
       [14, 18, 22]])

In [27]:
print(aux[:,:,:2]) # primeras 2 columnas de cada capa de profundidad, todas las filas 

print()

print(aux[:,:,:2].shape)


[[[ 0  1]
  [ 4  5]
  [ 8  9]]

 [[12 13]
  [16 17]
  [20 21]]]

(2, 3, 2)


In [29]:
print(aux[:,:,2:]) # últimas 2 columnas de cada capa de profundidad, todas las filas

print()

print(aux[:,:,2:].shape)

[[[ 2  3]
  [ 6  7]
  [10 11]]

 [[14 15]
  [18 19]
  [22 23]]]

(2, 3, 2)
